# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenMind' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenMind
  pod 'Google/SignIn'
  pod 'CDAlertView'
  pod 'SpringIndicator'
  pod 'KDCircularProgress'
  pod 'SwiftCharts', '~> 0.5'

  target 'OpenMindTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
